// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: month.sql

package db

import (
	"context"
	"time"

	decimal "github.com/shopspring/decimal"
)

const addMonthBalance = `-- name: AddMonthBalance :one
UPDATE months
SET balance = balance + $1, final_balance = final_balance + $2
WHERE id = $3
RETURNING id, owner, title, description, year_id, balance, final_balance, start_date, end_date
`

type AddMonthBalanceParams struct {
	Amount      decimal.Decimal `json:"amount"`
	FinalAmount decimal.Decimal `json:"final_amount"`
	ID          int64           `json:"id"`
}

func (q *Queries) AddMonthBalance(ctx context.Context, arg AddMonthBalanceParams) (Month, error) {
	row := q.db.QueryRow(ctx, addMonthBalance, arg.Amount, arg.FinalAmount, arg.ID)
	var i Month
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Title,
		&i.Description,
		&i.YearID,
		&i.Balance,
		&i.FinalBalance,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const createMonth = `-- name: CreateMonth :one
INSERT INTO months (
  title,
  owner,
  description,
  year_id,
  start_date,
  end_date
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, owner, title, description, year_id, balance, final_balance, start_date, end_date
`

type CreateMonthParams struct {
	Title       string    `json:"title"`
	Owner       string    `json:"owner"`
	Description string    `json:"description"`
	YearID      int64     `json:"year_id"`
	StartDate   time.Time `json:"start_date"`
	EndDate     time.Time `json:"end_date"`
}

func (q *Queries) CreateMonth(ctx context.Context, arg CreateMonthParams) (Month, error) {
	row := q.db.QueryRow(ctx, createMonth,
		arg.Title,
		arg.Owner,
		arg.Description,
		arg.YearID,
		arg.StartDate,
		arg.EndDate,
	)
	var i Month
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Title,
		&i.Description,
		&i.YearID,
		&i.Balance,
		&i.FinalBalance,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const deleteMonth = `-- name: DeleteMonth :exec
DELETE FROM months WHERE id = $1
`

func (q *Queries) DeleteMonth(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMonth, id)
	return err
}

const getMonth = `-- name: GetMonth :one
SELECT id, owner, title, description, year_id, balance, final_balance, start_date, end_date FROM months
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMonth(ctx context.Context, id int64) (Month, error) {
	row := q.db.QueryRow(ctx, getMonth, id)
	var i Month
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Title,
		&i.Description,
		&i.YearID,
		&i.Balance,
		&i.FinalBalance,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const getMonthForUpdate = `-- name: GetMonthForUpdate :one
SELECT id, owner, title, description, year_id, balance, final_balance, start_date, end_date FROM months
WHERE id = $1 LIMIT 1 FOR NO KEY UPDATE
`

func (q *Queries) GetMonthForUpdate(ctx context.Context, id int64) (Month, error) {
	row := q.db.QueryRow(ctx, getMonthForUpdate, id)
	var i Month
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Title,
		&i.Description,
		&i.YearID,
		&i.Balance,
		&i.FinalBalance,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const listMonths = `-- name: ListMonths :many
SELECT id, owner, title, description, year_id, balance, final_balance, start_date, end_date FROM months
WHERE owner = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListMonthsParams struct {
	Owner  string `json:"owner"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListMonths(ctx context.Context, arg ListMonthsParams) ([]Month, error) {
	rows, err := q.db.Query(ctx, listMonths, arg.Owner, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Month{}
	for rows.Next() {
		var i Month
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Title,
			&i.Description,
			&i.YearID,
			&i.Balance,
			&i.FinalBalance,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMonth = `-- name: UpdateMonth :one
UPDATE months
SET title = $2, description = $3, year_id = $4, start_date = $5, end_date = $6
WHERE id = $1
RETURNING id, owner, title, description, year_id, balance, final_balance, start_date, end_date
`

type UpdateMonthParams struct {
	ID          int64     `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	YearID      int64     `json:"year_id"`
	StartDate   time.Time `json:"start_date"`
	EndDate     time.Time `json:"end_date"`
}

func (q *Queries) UpdateMonth(ctx context.Context, arg UpdateMonthParams) (Month, error) {
	row := q.db.QueryRow(ctx, updateMonth,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.YearID,
		arg.StartDate,
		arg.EndDate,
	)
	var i Month
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Title,
		&i.Description,
		&i.YearID,
		&i.Balance,
		&i.FinalBalance,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}
