// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	AddMonthBalance(ctx context.Context, arg AddMonthBalanceParams) (Month, error)
	AddYearBalance(ctx context.Context, arg AddYearBalanceParams) (Year, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateLine(ctx context.Context, arg CreateLineParams) (Line, error)
	CreateMonth(ctx context.Context, arg CreateMonthParams) (Month, error)
	CreateRecLine(ctx context.Context, arg CreateRecLineParams) (Recline, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateYear(ctx context.Context, arg CreateYearParams) (Year, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteCategory(ctx context.Context, id int64) error
	DeleteLine(ctx context.Context, id int64) error
	DeleteMonth(ctx context.Context, id int64) error
	DeleteRecLine(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, username string) error
	DeleteYear(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetCategoryForUpdate(ctx context.Context, id int64) (Category, error)
	GetLine(ctx context.Context, id int64) (Line, error)
	GetLineForUpdate(ctx context.Context, id int64) (Line, error)
	GetMonth(ctx context.Context, id int64) (Month, error)
	GetMonthForUpdate(ctx context.Context, id int64) (Month, error)
	GetRecLine(ctx context.Context, id int64) (Recline, error)
	GetRecLineForUpdate(ctx context.Context, id int64) (Recline, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetYear(ctx context.Context, id int64) (Year, error)
	GetYearForUpdate(ctx context.Context, id int64) (Year, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error)
	ListExplicitLines(ctx context.Context, arg ListExplicitLinesParams) ([]ListExplicitLinesRow, error)
	ListLines(ctx context.Context, arg ListLinesParams) ([]Line, error)
	ListMonths(ctx context.Context, arg ListMonthsParams) ([]Month, error)
	ListRecLines(ctx context.Context, arg ListRecLinesParams) ([]Recline, error)
	ListYears(ctx context.Context, arg ListYearsParams) ([]Year, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateLine(ctx context.Context, arg UpdateLineParams) (Line, error)
	UpdateMonth(ctx context.Context, arg UpdateMonthParams) (Month, error)
	UpdateRecLine(ctx context.Context, arg UpdateRecLineParams) (Recline, error)
	UpdateYear(ctx context.Context, arg UpdateYearParams) (Year, error)
}

var _ Querier = (*Queries)(nil)
